server:
  port: 10000

spring:
  application:
    name: mooc-authorize
  #配置数据库连接参数
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.99.220.103:3306/mooc?characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: y1234567
#redis配置  host地址  端口port redis默认是6379 还有密码
  redis:
    host: 47.99.220.103
    port: 6379
    password: y1234567
  #rabbitmq配置
  rabbitmq:
    host: 192.168.23.21
    virtual-host: /xmz/test
    port: 5672
    username: admin
    password: admin

#rsa公钥、私钥
mooc:
  rsa:
    privateKey: MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBAIInYxQKB4ogMqv2oaQzcL7V5e58S7E487wr2HA3Ceutlik44ZNQxjxE/zlPSkGKhSF3U3aOsEF2+tvUacYYi3+v0cU/N6FAsTj0wbZEysO6MCnDlnwkePZKKWnuizhCzcKA5BFqG6gdHeimuCBE7bm4V30o0KR5rp9+w5T9zJbrAgMBAAECgYBXQtb/oXXKmqm+d32KHF7z427kRPtul3N6bp8PJSeGlnw9qQA8B4TQ9aV0I//yD1AQzvLrYuEzEvU/m5tLEDu95IBjkBBqLnVyOIgZWxZIlsbbNKC7GAj6faSBbyNTX+WU8cklKhjs4yRudYH5/3N+r9TEJsgc6xZHnmjNHFyZEQJBAOqNxU7Fc7ZYqWsMo+Tzzp6r69cXE+/rTaqsLEQ2aejOVs7yXnpJRnsaVPqZDHr+f7RIAf2+fkyQyKydIRF1M+MCQQCODeoKoRzgx9mVf2+WbZFxcgpvMVS6vksRME3/mZf9wzIQv53ilwAPY3NEXWXZY4AfEALsNzYygTOufzOB089ZAkEAqBFOAFObxl1hiENWbQgGVcv7AfSXZKLG1DTqwzX6TccMjN0+tYEr76m+mpJwTvFtsFConJmTBmn4YTd2KnxA4QJAD7BNttrQW6r2xuIKKuzy8TqNGHa0SuOVWtKg6qfF94rFTsA66bmPkiODqXs/MmEg101nZTs7yxwl3xHBWIdSEQJBAN4g2mrX6V0rYhC9n6L4jywJiRQFKfjxP5rmjMlAr/rQxzJQe9zOjpf6O59QyCx3NF+zXmtqXynpgF6JX+T+RFM=
    publicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCCJ2MUCgeKIDKr9qGkM3C+1eXufEuxOPO8K9hwNwnrrZYpOOGTUMY8RP85T0pBioUhd1N2jrBBdvrb1GnGGIt/r9HFPzehQLE49MG2RMrDujApw5Z8JHj2Silp7os4Qs3CgOQRahuoHR3oprggRO25uFd9KNCkea6ffsOU/cyW6wIDAQAB
  #管理员账号
  superAdmin:
    username: admin
    password: root

logging:
  level:
    cn.edu.lingnan.mooc.dao: trace

#向eureka注册
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/