server:
  port: 9004


#向eureka注册
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/

#服务名
spring:
  application:
    name: mooc-message
  #配置数据库连接参数
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.99.220.103:3306/mooc?characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: y1234567
  #执行数据库操作时，控制台打印sql语句
  jpa:
    show-sql: true
    properties:
      hibernate:
      format_sql: true
    hibernate:
      ddl-auto: update
  #redis配置
  redis:
    host: 47.99.220.103
    port: 6379
    password: y1234567
  #rabbitmq配置
  rabbitmq:
    host: 192.168.23.21
    virtual-host: /xmz/test
    port: 5672
    username: admin
    password: admin

  #时间格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

#mybatis配置文件位置
mybatis:
  #指定xml文件存放路径
  mapper-locations: classpath:mapper/*.xml
  #驼峰命名转换
  configuration:
    map-underscore-to-camel-case: true

#mybatis设置日志级别为trace，输出sql执行过程
logging:
  level:
    cn:
      edu:
        lingnan:
          mooc:
            message:
              mapper: trace

#配置队列名
constant:
  mq:
    messageQueue: mooc.mq.messageQueue




