#服务端口
server:
  port: 9005

spring:
  #es连接配置
  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300
      cluster-name: my-application

  #配置数据库连接参数
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mooc?characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: root
  #执行数据库操作时，控制台打印sql语句
  jpa:
    show-sql: true
    properties:
      hibernate:
      format_sql: true
    hibernate:
      ddl-auto: update