#服务端口
server:
  port: 9005

spring:
#  #es连接配置
  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300
      cluster-name: my-application
  #ES http rest连接
#  elasticsearch:
#    rest:
#      uris: http://127.0.0.1:9200

  #配置mysql数据库连接参数
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mooc?characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: root
  #jpa执行数据库操作时，控制台打印sql语句
  jpa:
    show-sql: true
    properties:
      hibernate:
      format_sql: true
    hibernate:
      ddl-auto: update
  #redis数据库配置
  redis:
    host: localhost
    port: 6379
    database: 0
    password: root

#mybatis配置文件位置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  #驼峰命名转换
  configuration:
    map-underscore-to-camel-case: true


#mybatis设置日志级别为trace，输出sql执行过程
logging:
  level:
    cn.edu.lingnan.mooc.statistics.mapper: trace