server:
  port: 9090

#向eureka注册
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/

spring:
  application:
    name: mooc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启根据微服务名称自动转发
          lower-case-service-id: true  #微服务名称以小写形式呈现
      routes:
        - id: mooc-core            #路由ID，没有固定规则，但要求唯一
          uri: lb://mooc-core   #匹配后提供服务的路由地址
          predicates:
            - Path=/core/**     #断言： 路径相匹配的进行路由,注意这里的Path首字母大写

        - id: mooc-authorize            #路由ID，没有固定规则，但要求唯一
          uri: lb://mooc-authorize    #匹配后提供服务的路由地址
          predicates:
            - Path=/authorize/**     #断言： 路径相匹配的进行路由,注意这里的Path首字母大写


#        - id: payment_routh2
#          uri: http://localhost:8001
#          predicates:
#            - Path=/payment/lb/**
